#Requires -Version 7.4

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

function New-TestPackage {
    param(
        [Parameter(Mandatory)]
        [string]$Id,

        [Parameter(Mandatory)]
        [string]$Name,

        [Parameter(Mandatory)]
        [string]$Version,

        [string]$License,

        [string]$ManifestPath
    )

    return [ordered]@{
        id = $Id
        name = $Name
        version = $Version
        license = $License
        license_file = $null
        manifest_path = $ManifestPath
        source = $null
        dependencies = @()
        targets = @()
        features = [ordered]@{}
        authors = @()
    }
}

function New-TestDepKind {
    param(
        [string]$Kind
    )

    return [ordered]@{ kind = $Kind; target = $null }
}

function New-TestNode {
    param(
        [Parameter(Mandatory)]
        [string]$Id,

        [object[]]$Deps = @()
    )

    return [ordered]@{ id = $Id; deps = @($Deps) }
}

function New-TestDep {
    param(
        [Parameter(Mandatory)]
        [string]$Pkg,

        [string]$Kind
    )

    return [ordered]@{
        name = ($Pkg -replace '[^A-Za-z0-9]', '_')
        pkg = $Pkg
        dep_kinds = @((New-TestDepKind -Kind $Kind))
    }
}

# Local Windows-style home/build paths embedded only inside opaque package
# "id" and workspace fields, mirroring real `cargo metadata` output where
# path-based package ids and workspace_root/target_directory contain absolute
# filesystem paths. These must never reach the emitted SBOM JSON.
$script:ForbiddenLocalMarker = 'C:\Users\exampleuser\workspace'

function New-TestMetadataDocument {
    param(
        [Parameter(Mandatory)]
        [object[]]$Packages,

        [Parameter(Mandatory)]
        [string[]]$WorkspaceMemberIds,

        [Parameter(Mandatory)]
        [object[]]$Nodes
    )

    return [ordered]@{
        packages = @($Packages)
        workspace_members = @($WorkspaceMemberIds)
        resolve = [ordered]@{ nodes = @($Nodes) }
        target_directory = "$script:ForbiddenLocalMarker\target"
        workspace_root = $script:ForbiddenLocalMarker
        version = 1
        metadata = $null
    }
}

$root = Join-Path (
    [IO.Path]::GetTempPath()
) "konclave-rust-sbom-test-$([Guid]::NewGuid().ToString('N'))"
New-Item -ItemType Directory -Path $root | Out-Null
try {
    [IO.File]::WriteAllText(
        (Join-Path $root 'Cargo.lock'),
        @'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "demo-root"
version = "0.1.0"

[[package]]
name = "demo-normal-dep"
version = "1.2.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111aaaa"

[[package]]
name = "demo-transitive-dep"
version = "0.4.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2222222222222222222222222222222222222222222222222222222222bbbb"
'@,
        [Text.UTF8Encoding]::new($false)
    )

    $rootPkgId = "demo-root 0.1.0 (path+file:///$($script:ForbiddenLocalMarker.Replace('\','/'))/demo-root)"
    $rootTwoPkgId = 'id-root-two'
    $normalDepId = 'id-normal-dep'
    $transitiveDepId = 'id-transitive-dep'
    $devOnlyId = 'id-dev-only-dep'
    $buildOnlyId = 'id-build-only-dep'
    $unreachableId = 'id-unreachable-dep'
    $windowsOnlyId = 'id-windows-only-dep'

    $basePackages = @(
        (New-TestPackage -Id $rootPkgId -Name 'demo-root' -Version '0.1.0' -ManifestPath "$script:ForbiddenLocalMarker\demo-root\Cargo.toml"),
        (New-TestPackage -Id $rootTwoPkgId -Name 'demo-root-two' -Version '0.1.0'),
        (New-TestPackage -Id $normalDepId -Name 'demo-normal-dep' -Version '1.2.3' -License 'MIT OR Apache-2.0'),
        (New-TestPackage -Id $transitiveDepId -Name 'demo-transitive-dep' -Version '0.4.0' -License 'MIT'),
        (New-TestPackage -Id $devOnlyId -Name 'demo-dev-only-dep' -Version '9.0.0'),
        (New-TestPackage -Id $buildOnlyId -Name 'demo-build-only-dep' -Version '8.0.0'),
        (New-TestPackage -Id $unreachableId -Name 'demo-unreachable-dep' -Version '7.0.0')
    )
    $windowsOnlyPackage = New-TestPackage -Id $windowsOnlyId -Name 'demo-windows-only-dep' -Version '5.0.0'

    $rootNode = New-TestNode -Id $rootPkgId -Deps @(
        (New-TestDep -Pkg $normalDepId),
        (New-TestDep -Pkg $devOnlyId -Kind 'dev'),
        (New-TestDep -Pkg $buildOnlyId -Kind 'build')
    )
    $rootTwoNode = New-TestNode -Id $rootTwoPkgId -Deps @(
        (New-TestDep -Pkg $transitiveDepId)
    )
    $normalDepNode = New-TestNode -Id $normalDepId -Deps @(
        (New-TestDep -Pkg $transitiveDepId)
    )
    $transitiveDepNode = New-TestNode -Id $transitiveDepId
    $devOnlyNode = New-TestNode -Id $devOnlyId
    $buildOnlyNode = New-TestNode -Id $buildOnlyId
    $unreachableNode = New-TestNode -Id $unreachableId

    $linuxMetadataPath = Join-Path $root 'metadata-linux.json'
    $linuxDocument = New-TestMetadataDocument `
        -Packages $basePackages `
        -WorkspaceMemberIds @($rootPkgId, $rootTwoPkgId) `
        -Nodes @($rootNode, $rootTwoNode, $normalDepNode, $transitiveDepNode, $devOnlyNode, $buildOnlyNode, $unreachableNode)
    [IO.File]::WriteAllText(
        $linuxMetadataPath,
        ($linuxDocument | ConvertTo-Json -Depth 20),
        [Text.UTF8Encoding]::new($false)
    )

    $windowsRootNode = New-TestNode -Id $rootPkgId -Deps @(
        (New-TestDep -Pkg $normalDepId),
        (New-TestDep -Pkg $windowsOnlyId),
        (New-TestDep -Pkg $devOnlyId -Kind 'dev'),
        (New-TestDep -Pkg $buildOnlyId -Kind 'build')
    )
    $windowsOnlyNode = New-TestNode -Id $windowsOnlyId
    $windowsMetadataPath = Join-Path $root 'metadata-windows.json'
    $windowsDocument = New-TestMetadataDocument `
        -Packages ($basePackages + @($windowsOnlyPackage)) `
        -WorkspaceMemberIds @($rootPkgId) `
        -Nodes @($windowsRootNode, $normalDepNode, $transitiveDepNode, $devOnlyNode, $buildOnlyNode, $unreachableNode, $windowsOnlyNode)
    [IO.File]::WriteAllText(
        $windowsMetadataPath,
        ($windowsDocument | ConvertTo-Json -Depth 20),
        [Text.UTF8Encoding]::new($false)
    )

    $cliPath = Join-Path $PSScriptRoot 'New-ReleaseRustSbom.ps1'

    $linuxOutputFirst = Join-Path $root 'linux.first.cdx.json'
    $linuxOutputSecond = Join-Path $root 'linux.second.cdx.json'
    foreach ($output in @($linuxOutputFirst, $linuxOutputSecond)) {
        & $cliPath `
            -ProjectRoot $root `
            -Target 'x86_64-unknown-linux-gnu' `
            -ArtifactId 'konclave-client-linux-x64' `
            -ArtifactName 'konclave-client' `
            -ArtifactVersion '0.1.0' `
            -RootPackageName @('demo-root') `
            -OutputPath $output `
            -MetadataPath $linuxMetadataPath
    }

    if ((Get-FileHash $linuxOutputFirst).Hash -cne (Get-FileHash $linuxOutputSecond).Hash) {
        throw 'Rust SBOM generation is not deterministic.'
    }

    $linuxJson = [IO.File]::ReadAllText($linuxOutputFirst, [Text.Encoding]::UTF8)
    $linux = $linuxJson | ConvertFrom-Json -Depth 20

    if ($linux.bomFormat -cne 'CycloneDX' -or $linux.specVersion -cne '1.6') {
        throw 'Rust SBOM did not emit the expected CycloneDX 1.6 shape.'
    }
    if ($linux.PSObject.Properties['serialNumber'] -or $linux.metadata.PSObject.Properties['timestamp']) {
        throw 'Rust SBOM emitted a non-deterministic serialNumber or timestamp.'
    }
    if (
        [string]$linux.metadata.component.'bom-ref' -cne 'konclave-client-linux-x64' -or
        [string]$linux.metadata.component.name -cne 'konclave-client' -or
        [string]$linux.metadata.component.version -cne '0.1.0'
    ) {
        throw 'Rust SBOM metadata component does not describe the release artifact.'
    }

    $names = [string[]]@($linux.components | ForEach-Object { [string]$_.name })
    $expectedNames = [string[]]@('demo-root', 'demo-normal-dep', 'demo-transitive-dep')
    [Array]::Sort($expectedNames, [StringComparer]::Ordinal)
    $actualNames = [string[]]@($names.Clone())
    [Array]::Sort($actualNames, [StringComparer]::Ordinal)
    if (@(Compare-Object $actualNames $expectedNames -CaseSensitive).Count -gt 0) {
        throw 'Rust SBOM dependency closure did not include exactly the reachable normal-dependency packages.'
    }

    $bomRefs = [string[]]@($linux.components | ForEach-Object { [string]$_.'bom-ref' })
    $sortedBomRefs = [string[]]@($bomRefs.Clone())
    [Array]::Sort($sortedBomRefs, [StringComparer]::Ordinal)
    if (@(Compare-Object $bomRefs $sortedBomRefs -CaseSensitive -SyncWindow 0).Count -gt 0) {
        throw 'Rust SBOM components are not sorted ordinally.'
    }

    $normalComponent = $linux.components | Where-Object { [string]$_.name -ceq 'demo-normal-dep' }
    if (
        [string]$normalComponent.purl -cne 'pkg:cargo/demo-normal-dep@1.2.3' -or
        [string]$normalComponent.'bom-ref' -cne 'pkg:cargo/demo-normal-dep@1.2.3' -or
        [string]$normalComponent.licenses[0].expression -cne 'MIT OR Apache-2.0' -or
        [string]$normalComponent.hashes[0].alg -cne 'SHA-256' -or
        [string]$normalComponent.hashes[0].content -cne '1111111111111111111111111111111111111111111111111111111111aaaa'
    ) {
        throw 'Rust SBOM did not emit the expected purl, license, or checksum for a registry dependency.'
    }

    $rootComponent = $linux.components | Where-Object { [string]$_.name -ceq 'demo-root' }
    if ($rootComponent.PSObject.Properties['hashes']) {
        throw 'Rust SBOM emitted a checksum for a local workspace package.'
    }

    $dependencyByRef = @{}
    foreach ($dependency in $linux.dependencies) {
        $dependencyByRef[[string]$dependency.ref] = [string[]]@($dependency.dependsOn)
    }
    $rootBomRef = [string]$rootComponent.'bom-ref'
    $normalBomRef = [string]$normalComponent.'bom-ref'
    $transitiveComponent = $linux.components | Where-Object { [string]$_.name -ceq 'demo-transitive-dep' }
    $transitiveBomRef = [string]$transitiveComponent.'bom-ref'
    if (
        (Compare-Object $dependencyByRef['konclave-client-linux-x64'] @($rootBomRef) -CaseSensitive).Count -gt 0 -or
        (Compare-Object $dependencyByRef[$rootBomRef] @($normalBomRef) -CaseSensitive).Count -gt 0 -or
        (Compare-Object $dependencyByRef[$normalBomRef] @($transitiveBomRef) -CaseSensitive).Count -gt 0 -or
        $dependencyByRef[$transitiveBomRef].Count -ne 0
    ) {
        throw 'Rust SBOM dependency graph does not connect artifact, roots, and packages as expected.'
    }

    foreach (
        $forbidden in @(
            'file://',
            'C:\Users',
            'exampleuser',
            'target_directory',
            'workspace_root',
            'manifest_path',
            $rootPkgId,
            $normalDepId,
            $root
        )
    ) {
        if ($linuxJson.Contains($forbidden, [StringComparison]::OrdinalIgnoreCase)) {
            throw "Rust SBOM leaked a forbidden local identifier: $forbidden"
        }
    }

    $windowsOutput = Join-Path $root 'windows.cdx.json'
    & $cliPath `
        -ProjectRoot $root `
        -Target 'x86_64-pc-windows-msvc' `
        -ArtifactId 'konclave-client-windows-x64' `
        -ArtifactName 'konclave-client' `
        -ArtifactVersion '0.1.0' `
        -RootPackageName @('demo-root') `
        -OutputPath $windowsOutput `
        -MetadataPath $windowsMetadataPath
    $windows = [IO.File]::ReadAllText($windowsOutput, [Text.Encoding]::UTF8) | ConvertFrom-Json -Depth 20
    $windowsNames = [string[]]@($windows.components | ForEach-Object { [string]$_.name })
    if ($windowsNames -notcontains 'demo-windows-only-dep') {
        throw 'Rust SBOM did not include a package present only in the target-selected graph.'
    }
    if ($names -contains 'demo-windows-only-dep') {
        throw 'Rust SBOM included a package outside the requested target-selected graph.'
    }

    $multiRootOutput = Join-Path $root 'multi-root.cdx.json'
    & $cliPath `
        -ProjectRoot $root `
        -Target 'x86_64-unknown-linux-gnu' `
        -ArtifactId 'konclave-client-linux-x64' `
        -ArtifactName 'konclave-client' `
        -ArtifactVersion '0.1.0' `
        -RootPackageName @('demo-root', 'demo-root-two') `
        -OutputPath $multiRootOutput `
        -MetadataPath $linuxMetadataPath
    $multiRoot = [IO.File]::ReadAllText($multiRootOutput, [Text.Encoding]::UTF8) | ConvertFrom-Json -Depth 20
    $multiRootNames = [string[]]@($multiRoot.components | ForEach-Object { [string]$_.name })
    if ($multiRootNames -notcontains 'demo-root-two') {
        throw 'Rust SBOM did not include a second requested root package.'
    }
    $multiRootDependencyByRef = @{}
    foreach ($dependency in $multiRoot.dependencies) {
        $multiRootDependencyByRef[[string]$dependency.ref] = [string[]]@($dependency.dependsOn)
    }
    $rootTwoComponent = $multiRoot.components | Where-Object { [string]$_.name -ceq 'demo-root-two' }
    $expectedArtifactDeps = [string[]]@($rootBomRef, [string]$rootTwoComponent.'bom-ref')
    [Array]::Sort($expectedArtifactDeps, [StringComparer]::Ordinal)
    if (
        (Compare-Object `
            $multiRootDependencyByRef['konclave-client-linux-x64'] `
            $expectedArtifactDeps `
            -CaseSensitive -SyncWindow 0
        ).Count -gt 0
    ) {
        throw 'Rust SBOM did not connect the release artifact to every requested root package.'
    }
    if (
        (Compare-Object $multiRootDependencyByRef[[string]$rootTwoComponent.'bom-ref'] @($transitiveBomRef) -CaseSensitive).Count -gt 0
    ) {
        throw 'Rust SBOM did not preserve a second root package dependency edge.'
    }

    $collisionMetadataPath = Join-Path $root 'metadata-collision.json'
    $collisionForkId = 'id-normal-dep-fork'
    $collisionForkPackage = New-TestPackage -Id $collisionForkId -Name 'demo-normal-dep' -Version '1.2.3'
    $collisionRootNode = New-TestNode -Id $rootPkgId -Deps @(
        (New-TestDep -Pkg $normalDepId),
        (New-TestDep -Pkg $collisionForkId)
    )
    $collisionForkNode = New-TestNode -Id $collisionForkId
    $collisionDocument = New-TestMetadataDocument `
        -Packages ($basePackages + @($collisionForkPackage)) `
        -WorkspaceMemberIds @($rootPkgId) `
        -Nodes @($collisionRootNode, $normalDepNode, $transitiveDepNode, $collisionForkNode, $devOnlyNode, $buildOnlyNode, $unreachableNode)
    [IO.File]::WriteAllText(
        $collisionMetadataPath,
        ($collisionDocument | ConvertTo-Json -Depth 20),
        [Text.UTF8Encoding]::new($false)
    )
    $collisionThrew = $false
    try {
        & $cliPath `
            -ProjectRoot $root `
            -Target 'x86_64-unknown-linux-gnu' `
            -ArtifactId 'konclave-client-linux-x64' `
            -ArtifactName 'konclave-client' `
            -ArtifactVersion '0.1.0' `
            -RootPackageName @('demo-root') `
            -OutputPath (Join-Path $root 'collision.cdx.json') `
            -MetadataPath $collisionMetadataPath
    }
    catch {
        $collisionThrew = $true
    }
    if (-not $collisionThrew) {
        throw 'Rust SBOM generation accepted two distinct packages colliding on the same bom-ref.'
    }

    Write-Output 'Rust SBOM closure, ordering, checksum, and collision tests passed.'
}
finally {
    if (Test-Path -LiteralPath $root) {
        Remove-Item -LiteralPath $root -Recurse -Force
    }
}
