import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import {
  decodeFrameLength,
  decodeHandshakeMessage,
  encodeFrame,
  encodeHandshakeMessage,
  frameHeaderLength,
  maxAuthenticatedFrameBytes,
  maxPreauthFrameBytes,
  type HandshakeMessage,
} from '../src/adapter/frame.js';
import {
  decodeAdapterResponse,
  encodeAdapterRequest,
  maxClaimBatch,
  maxEventTextBytes,
  maxWaitMilliseconds,
  notificationIdLength,
  routedIdLength,
} from '../src/adapter/session.js';

interface EncodedVector {
  readonly encoded: string;
}

interface SessionVectors {
  readonly protocolVersion: number;
  readonly handshake: {
    readonly adapterHello: EncodedVector & { consumer: string; challenge: string };
    readonly daemonAuth: EncodedVector & { profile: string; challenge: string; proof: string };
    readonly adapterAuth: EncodedVector & { proof: string };
  };
  readonly requests: {
    readonly waitAndClaim: EncodedVector & { maxEvents: number; waitMilliseconds: number };
    readonly acknowledge: EncodedVector & { notificationId: string; leaseGeneration: number };
    readonly release: EncodedVector & { notificationId: string; leaseGeneration: number };
    readonly status: EncodedVector;
  };
  readonly responses: {
    readonly accepted: EncodedVector;
    readonly emptyBatch: EncodedVector;
    readonly status: EncodedVector & {
      pendingEvents: number;
      claimedEvents: number;
      watchedConversations: number;
      deliveryDegraded: boolean;
    };
    readonly failure: EncodedVector & { code: string };
    readonly batch: EncodedVector & {
      notificationId: string;
      leaseGeneration: number;
      sequence: number;
      conversation: string;
      sender: string;
      relayCursor: number;
      events: readonly { kind: string; text?: string; device?: string; role?: string }[];
    };
  };
  readonly bounds: Record<string, number>;
}

// Generated by the Rust implementation. Reading them as data means a layout change
// fails here rather than silently desynchronizing the two sides.
const vectors = JSON.parse(
  readFileSync(
    join(
      import.meta.dirname,
      '..',
      '..',
      '..',
      'fixtures',
      'adapter',
      'v1',
      'session-operations.json',
    ),
    'utf8',
  ),
) as SessionVectors;

describe('adapter session bounds parity', () => {
  it('implements the same bounds the other side enforces', () => {
    expect(frameHeaderLength).toBe(vectors.bounds.frameHeaderLength);
    expect(maxPreauthFrameBytes).toBe(vectors.bounds.maxPreauthFrameBytes);
    expect(maxAuthenticatedFrameBytes).toBe(vectors.bounds.maxAuthenticatedFrameBytes);
    expect(maxClaimBatch).toBe(vectors.bounds.maxClaimBatch);
    expect(maxWaitMilliseconds).toBe(vectors.bounds.maxWaitMilliseconds);
    expect(maxEventTextBytes).toBe(vectors.bounds.maxEventTextBytes);
    expect(notificationIdLength).toBe(vectors.bounds.notificationIdLength);
    expect(routedIdLength).toBe(vectors.bounds.routedIdLength);
  });
});

describe('adapter request parity', () => {
  it('encodes a bounded wait exactly as the other side decodes it', () => {
    const vector = vectors.requests.waitAndClaim;
    expect(
      encodeAdapterRequest({
        kind: 'wait-and-claim',
        maxEvents: vector.maxEvents,
        waitMilliseconds: vector.waitMilliseconds,
      }).toString('hex'),
    ).toBe(vector.encoded);
  });

  it('encodes claim transitions exactly as the other side decodes them', () => {
    const acknowledge = vectors.requests.acknowledge;
    expect(
      encodeAdapterRequest({
        kind: 'acknowledge',
        notificationId: Buffer.from(acknowledge.notificationId, 'hex'),
        leaseGeneration: acknowledge.leaseGeneration,
      }).toString('hex'),
    ).toBe(acknowledge.encoded);

    const release = vectors.requests.release;
    expect(
      encodeAdapterRequest({
        kind: 'release',
        notificationId: Buffer.from(release.notificationId, 'hex'),
        leaseGeneration: release.leaseGeneration,
      }).toString('hex'),
    ).toBe(release.encoded);
  });

  it('encodes a status request exactly as the other side decodes it', () => {
    expect(encodeAdapterRequest({ kind: 'status' }).toString('hex')).toBe(
      vectors.requests.status.encoded,
    );
  });

  it('rejects requests outside their bounds before they reach the wire', () => {
    const notificationId = Buffer.alloc(notificationIdLength);
    for (const request of [
      { kind: 'wait-and-claim', maxEvents: 0, waitMilliseconds: 1 },
      { kind: 'wait-and-claim', maxEvents: maxClaimBatch + 1, waitMilliseconds: 1 },
      { kind: 'wait-and-claim', maxEvents: 1, waitMilliseconds: maxWaitMilliseconds + 1 },
      { kind: 'acknowledge', notificationId: Buffer.alloc(8), leaseGeneration: 1 },
      { kind: 'acknowledge', notificationId, leaseGeneration: -1 },
    ] as const) {
      expect(() => encodeAdapterRequest(request)).toThrow();
    }
  });
});

describe('adapter response parity', () => {
  it('decodes an accepted transition and an expired wait as distinct answers', () => {
    expect(decodeAdapterResponse(Buffer.from(vectors.responses.accepted.encoded, 'hex'))).toEqual({
      kind: 'accepted',
    });
    expect(decodeAdapterResponse(Buffer.from(vectors.responses.emptyBatch.encoded, 'hex'))).toEqual(
      {
        kind: 'batch',
        events: [],
      },
    );
  });

  it('decodes status exactly as the other side reported it', () => {
    const vector = vectors.responses.status;
    expect(decodeAdapterResponse(Buffer.from(vector.encoded, 'hex'))).toEqual({
      kind: 'status',
      status: {
        pendingEvents: vector.pendingEvents,
        claimedEvents: vector.claimedEvents,
        watchedConversations: vector.watchedConversations,
        deliveryDegraded: vector.deliveryDegraded,
      },
    });
  });

  it('decodes a failure code', () => {
    expect(decodeAdapterResponse(Buffer.from(vectors.responses.failure.encoded, 'hex'))).toEqual({
      kind: 'failure',
      code: vectors.responses.failure.code,
    });
  });

  it('decodes every event kind produced by the other side', () => {
    const vector = vectors.responses.batch;
    const response = decodeAdapterResponse(Buffer.from(vector.encoded, 'hex'));
    expect(response.kind).toBe('batch');
    if (response.kind !== 'batch') {
      return;
    }

    expect(response.events).toHaveLength(vector.events.length);
    response.events.forEach((event, index) => {
      const expected = vector.events[index];
      expect(event.notificationId.toString('hex')).toBe(vector.notificationId);
      expect(event.leaseGeneration).toBe(vector.leaseGeneration);
      expect(event.sequence).toBe(vector.sequence);
      expect(event.conversation.toString('hex')).toBe(vector.conversation);
      expect(event.sender.toString('hex')).toBe(vector.sender);
      expect(event.relayCursor).toBe(vector.relayCursor);
      expect(event.payload.kind).toBe(expected?.kind);

      if (event.payload.kind === 'application-text') {
        expect(event.payload.text).toBe(expected?.text);
      } else {
        expect(event.payload.device.toString('hex')).toBe(expected?.device);
        if ('role' in event.payload) {
          expect(event.payload.role).toBe(expected?.role);
        }
      }
    });
  });

  it('rejects unknown kinds, trailing bytes, and truncation at every prefix', () => {
    expect(() => decodeAdapterResponse(Buffer.of(99))).toThrow();
    expect(() => decodeAdapterResponse(Buffer.alloc(0))).toThrow();
    expect(() =>
      decodeAdapterResponse(
        Buffer.concat([Buffer.from(vectors.responses.accepted.encoded, 'hex'), Buffer.of(0)]),
      ),
    ).toThrow();

    const batch = Buffer.from(vectors.responses.batch.encoded, 'hex');
    for (let length = 1; length < batch.length; length += 1) {
      expect(() => decodeAdapterResponse(batch.subarray(0, length))).toThrow();
    }
  });

  it('rejects a declared batch larger than its payload and above the maximum', () => {
    const empty = Buffer.from(vectors.responses.emptyBatch.encoded, 'hex');

    const overrun = Buffer.from(empty);
    overrun.writeUInt16BE(5, 1);
    expect(() => decodeAdapterResponse(overrun)).toThrow();

    const oversized = Buffer.from(empty);
    oversized.writeUInt16BE(maxClaimBatch + 1, 1);
    expect(() => decodeAdapterResponse(oversized)).toThrow();
  });

  it('rejects an unknown role and a malformed degraded flag', () => {
    const batch = Buffer.from(vectors.responses.batch.encoded, 'hex');
    const corrupted = Buffer.from(batch);
    corrupted[corrupted.length - routedIdLength - 1] = 9;
    expect(() => decodeAdapterResponse(corrupted)).toThrow();

    const status = Buffer.from(vectors.responses.status.encoded, 'hex');
    const badFlag = Buffer.from(status);
    badFlag[badFlag.length - 1] = 2;
    expect(() => decodeAdapterResponse(badFlag)).toThrow();
  });

  it('rejects a failure code that is not machine readable', () => {
    const failure = Buffer.from(vectors.responses.failure.encoded, 'hex');
    const corrupted = Buffer.from(failure);
    corrupted[2] = 0x20;
    expect(() => decodeAdapterResponse(corrupted)).toThrow();
  });
});

describe('adapter handshake framing parity', () => {
  const handshake = vectors.handshake;

  it('encodes and decodes an adapter hello exactly as the other side does', () => {
    const message: HandshakeMessage = {
      kind: 'adapter-hello',
      version: vectors.protocolVersion,
      consumer: handshake.adapterHello.consumer,
      challenge: Buffer.from(handshake.adapterHello.challenge, 'hex'),
    };
    expect(encodeHandshakeMessage(message).toString('hex')).toBe(handshake.adapterHello.encoded);
    expect(decodeHandshakeMessage(Buffer.from(handshake.adapterHello.encoded, 'hex'))).toEqual(
      message,
    );
  });

  it('encodes and decodes a daemon authentication exactly as the other side does', () => {
    const message: HandshakeMessage = {
      kind: 'daemon-auth',
      profile: handshake.daemonAuth.profile,
      challenge: Buffer.from(handshake.daemonAuth.challenge, 'hex'),
      proof: Buffer.from(handshake.daemonAuth.proof, 'hex'),
    };
    expect(encodeHandshakeMessage(message).toString('hex')).toBe(handshake.daemonAuth.encoded);
    expect(decodeHandshakeMessage(Buffer.from(handshake.daemonAuth.encoded, 'hex'))).toEqual(
      message,
    );
  });

  it('encodes and decodes an adapter authentication exactly as the other side does', () => {
    const message: HandshakeMessage = {
      kind: 'adapter-auth',
      proof: Buffer.from(handshake.adapterAuth.proof, 'hex'),
    };
    expect(encodeHandshakeMessage(message).toString('hex')).toBe(handshake.adapterAuth.encoded);
    expect(decodeHandshakeMessage(Buffer.from(handshake.adapterAuth.encoded, 'hex'))).toEqual(
      message,
    );
  });

  it('rejects unknown kinds, unimplemented versions, and trailing bytes', () => {
    expect(() => decodeHandshakeMessage(Buffer.of(99, 0, 0))).toThrow();
    expect(() => decodeHandshakeMessage(Buffer.alloc(0))).toThrow();

    const hello = Buffer.from(handshake.adapterHello.encoded, 'hex');
    const wrongVersion = Buffer.from(hello);
    wrongVersion.writeUInt16BE(vectors.protocolVersion + 1, 1);
    expect(() => decodeHandshakeMessage(wrongVersion)).toThrow();

    expect(() => decodeHandshakeMessage(Buffer.concat([hello, Buffer.of(0)]))).toThrow();
  });

  it('rejects truncation at every prefix', () => {
    for (const encoded of [
      handshake.adapterHello.encoded,
      handshake.daemonAuth.encoded,
      handshake.adapterAuth.encoded,
    ]) {
      const payload = Buffer.from(encoded, 'hex');
      for (let length = 1; length < payload.length; length += 1) {
        expect(() => decodeHandshakeMessage(payload.subarray(0, length))).toThrow();
      }
    }
  });

  it('rejects an empty or oversized declared identifier', () => {
    const hello = Buffer.from(handshake.adapterHello.encoded, 'hex');

    const empty = Buffer.from(hello);
    empty.writeUInt16BE(0, 3);
    expect(() => decodeHandshakeMessage(empty)).toThrow();

    const oversized = Buffer.from(hello);
    oversized.writeUInt16BE(hello.length + 64, 3);
    expect(() => decodeHandshakeMessage(oversized)).toThrow();
  });

  it('rejects a non-UTF-8 identifier rather than substituting a replacement character', () => {
    const hello = Buffer.from(handshake.adapterHello.encoded, 'hex');
    const corrupted = Buffer.from(hello);
    corrupted[5] = 0xff;
    expect(() => decodeHandshakeMessage(corrupted)).toThrow();
  });

  it('rejects a malformed length header', () => {
    expect(() => decodeFrameLength(Buffer.alloc(3), maxPreauthFrameBytes)).toThrow();
  });
});

describe('adapter framing', () => {
  it('round-trips a length header within its limit', () => {
    const payload = Buffer.from(vectors.responses.accepted.encoded, 'hex');
    const frame = encodeFrame(payload, maxAuthenticatedFrameBytes);
    expect(frame).toHaveLength(frameHeaderLength + payload.length);
    expect(
      decodeFrameLength(frame.subarray(0, frameHeaderLength), maxAuthenticatedFrameBytes),
    ).toBe(payload.length);
  });

  it('rejects an oversized declaration before a buffer is reserved', () => {
    const header = Buffer.alloc(frameHeaderLength);
    header.writeUInt32BE(maxPreauthFrameBytes + 1, 0);
    expect(() => decodeFrameLength(header, maxPreauthFrameBytes)).toThrow();
    expect(decodeFrameLength(header, maxAuthenticatedFrameBytes)).toBe(maxPreauthFrameBytes + 1);

    const zero = Buffer.alloc(frameHeaderLength);
    expect(() => decodeFrameLength(zero, maxPreauthFrameBytes)).toThrow();
  });

  it('refuses to frame an empty or oversized payload', () => {
    expect(() => encodeFrame(Buffer.alloc(0), maxPreauthFrameBytes)).toThrow();
    expect(() => encodeFrame(Buffer.alloc(8), 4)).toThrow();
  });
});
